### ISSUE TITLE
5.4.4 fails due to wrong umask and error

### ISSUE THREAD

**Issue by shashank-singhal** [radsec/CentOS7-CIS#13]
**Ansible Version - 2.9.9**

**ISSUE**
1. The umask variable `centos7cis_default_user_umask` changes to 023 instead of 027 when executing. _(not sure if it my system specific issue)_

https://github.com/radsec/CentOS7-CIS/blob/e1c381412ed035496bbc58261f35921bcb72a082/tasks/section5.yml#L1228

https://github.com/radsec/CentOS7-CIS/blob/e1c381412ed035496bbc58261f35921bcb72a082/tasks/section5.yml#L1243

2. The profiled_dir.files.path fails 
https://github.com/radsec/CentOS7-CIS/blob/e1c381412ed035496bbc58261f35921bcb72a082/tasks/section5.yml#L1275

with error as given below
```
TASK [CentOS7-CIS : SCORED | 5.4.4 | PATCH | Ensure default user umask is 027 or more restrictive] *********************************************************************
failed: [localhost] (item=profiled_dir.files[0].path) => {"ansible_loop_var": "item", "changed": false, "item": "profiled_dir.files[0].path", "msg": "Destination profiled_dir.files.path does not exist !", "rc": 257}
...ignoring

```

**Workaround** for `centos7cis_default_user_umask` changing to 023, run the ansible playbook with variables as command line argument by adding below argument
 `--extra-vars "centos7cis_default_user_umask=027"`
which will overpower the internal variable value.

**Viewpoint**
The structure of the profiled_dir.files is an array of dictionaries. Not sure how to get through this one using ansible at the moment.

**Comment by shashank-singhal** [comment]
I updated the centos7cis_default_user_umask in the main.yml to a string "027" and it picks 027 in the umask line.

**Comment by shashank-singhal** [comment]
Updated 
https://github.com/radsec/CentOS7-CIS/blob/e1c381412ed035496bbc58261f35921bcb72a082/tasks/section5.yml#L1275

to 

```
 with_items:
  - "{{ profiled_dir.files }}"
```

and 
https://github.com/radsec/CentOS7-CIS/blob/e1c381412ed035496bbc58261f35921bcb72a082/tasks/section5.yml#L1271

to 
`    dest: "{{ item.path}}"`

and now it works.

I am still learning ansible and was driven to the above refactoring by the errors provided by ansible. Please enlighten me if this change in syntax is due to the version I am using ansible 2.9.9

**Comment by rdiers** [comment]
I will look into resolving the issue this evening.
