### ISSUE TITLE
Variable is not defined rhel7cis_level1 causes execution failure

### ISSUE THREAD

**Issue by shashank-singhal** [radsec/CentOS7-CIS#23]
**Describe the bug**
The variable is not defined rhel7cis_level1 but used. Hence the execution fails.

**To Reproduce**
1. Run the script.

**Expected behavior**
No error should occur.

**Error**
TASK [CentOS7-CIS : SCORED | 2.2.1.3 | PATCH | Ensure chrony is configured] ********************************************************************************************
fatal: [localhost]: FAILED! => {"msg": "The conditional check 'centos7cis_level1 is defined and rhel7cis_level1' failed. The error was: error while evaluating conditional (centos7cis_level1 is defined and rhel7cis_level1): 'rhel7cis_level1' is undefined\n\nThe error appears to be in '/etc/ansible/roles/CentOS7-CIS/tasks/section2.yml': line 377, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: \"SCORED | 2.2.1.3 | PATCH | Ensure chrony is configured\"\n  ^ here\n"}

**Version Used**
Ansible 2.9.9
Latest repository.

**Comment by rdiers** [comment]
WIP.
