### ISSUE TITLE
Not able to login after applying playbook 

### ISSUE THREAD

**Issue by vmugutrao** [radsec/CentOS7-CIS#25]
I deploy this playbook on my test VM and I lost login connectivity, I am not able to fix it.
I had password less communication setup between my ansible node and VM and only that is working.

Any suggestion ?

**Comment by rdiers** [comment]
Depending on which level you applied, it probably altered your SSH server settings and turned off password based authentication which is an intended outcome. Please consider reading over section 5 to see what CIS hardening settings are applied. Closing the ticket as this is expected outcome and not a bug.
