### ISSUE TITLE
task referencing to template is missing

### ISSUE THREAD

**Issue by MeenachiSundaram** [radsec/CentOS7-CIS#5]
https://github.com/radsec/CentOS7-CIS/blob/master/tasks/section2.yml#L395

this throws the ansible execution error

in my case i added a file instead of template with default content in file

```
cat /etc/sysconfig/chronyd
# Command-line options for chronyd
OPTIONS=""
```

**Comment by rdiers** [comment]
Going to take a look at this issue and merge the similar RHEL CIS changes into this version.

**Comment by rdiers** [comment]
Resolved in latest PR to master.
