### ISSUE TITLE
Invalid character '-' in variable syslog-ng_installed

### ISSUE THREAD

**Issue by shashank-singhal** [radsec/CentOS7-CIS#7]
https://github.com/radsec/CentOS7-CIS/blob/a2e8fa83ebeaa3763288e27b58ff82d5389309ab/tasks/prelim.yml#L55

Ansible version - 2.9.9
Python version = 2.7.5

Issue - 
When running the playbook CentOS7-CIS_Benchmark_level1_and_level2.yml, there is execution error.

Reason -
The usage is `-` in the prelim.yml is invalid
`register: syslog-ng_installed`

Resolution - 
Replace `-` with `_` in the preim.yml file.

**Comment by rdiers** [comment]
Looking to resolve this tomorrow. Thanks.
